name: openHBot
services:
  - name: openhbot-service
    github:
      repo: Rbertolli/openHBot
      branch: master
    environment_slug: php
    build_command: "composer install --no-dev"
    run_command: "php -S 0.0.0.0:$PORT -t public"
    env_vars:
      - key: API_KEY
        value: "sua_chave_api_aqui"
      - key: API_SECRET
        value: "seu_segredo_api_aqui"
      - key: APP_ENV
        value: "production"
